function y = fun_BandFilter(x)
%  预处理输入 x
%    This function expects an input vector x.

% Generated by MATLAB(R) 24.2 and Signal Processing Toolbox 24.2.
% Generated on: 25-Nov-2025 14:25:29
y = x - mean(x);
y = bandpass(y,[0.0156 0.0219],'Steepness',0.8,'StopbandAttenuation',60);
