function y = fun_hilt_preprocess(x)
%  预处理输入 x
%    This function expects an input vector x.

% Generated by MATLAB(R) 24.2 and Signal Processing Toolbox 24.2.
% Generated on: 28-Nov-2025 17:11:41

% [y,~] = envelope(x);


% maximaSeparation = 200;
% [y,~] = envelope(x,maximaSeparation,'peak');

windowLength = 200;
[y,~] = envelope(x,windowLength,'rms');