function y = preprocess(x)
%  预处理输入 x
%    This function expects an input vector x.

% Generated by MATLAB(R) 24.2 and Signal Processing Toolbox 24.2.
% Generated on: 20-Nov-2025 08:58:37

% y = bandpass(x,[0.15 0.25],'Steepness',0.85,'StopbandAttenuation',60);

y = wdenoise(x, 8, ...
    'Wavelet', 'sym4', ...
    'DenoisingMethod', 'Bayes', ...
    'ThresholdRule', 'Median', ...
    'NoiseEstimate', 'LevelDependent');

windowLength = 320;
[y,~] = envelope(y,windowLength,'rms');
